services:
  - type: web
    name: real-estate-rate-estimation
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10
    region: oregon
